
###########################################################
# Clocks
###########################################################

# IO-Bank 705
set_property PACKAGE_PIN AW27 [get_ports CLKIN_p]
set_property PACKAGE_PIN AY27 [get_ports CLKIN_n]
set_property DATA_RATE DDR [get_ports CLKIN_p]
set_property IOSTANDARD LVDS15 [get_ports CLKIN_p]
set_property DC_BIAS DC_BIAS_0 [get_ports CLKIN_p]
set_property EQUALIZATION EQ_NONE [get_ports CLKIN_p]
set_property DIFF_TERM_ADV TERM_100 [get_ports CLKIN_p]
set_property DATA_RATE DDR [get_ports CLKIN_n]
set_property IOSTANDARD LVDS15 [get_ports CLKIN_n]
set_property DC_BIAS DC_BIAS_0 [get_ports CLKIN_n]
set_property EQUALIZATION EQ_NONE [get_ports CLKIN_n]
set_property DIFF_TERM_ADV TERM_100 [get_ports CLKIN_n]
create_clock -period 5.000 [get_ports CLKIN_p]


# IO-Bank 705
set_property PACKAGE_PIN AK8 [get_ports chipscope_clk_in_p_pin]
set_property PACKAGE_PIN AK7 [get_ports chipscope_clk_in_n_pin]
set_property IOSTANDARD LVDS15 [get_ports chipscope_clk_in_p_pin]
set_property DC_BIAS DC_BIAS_0 [get_ports chipscope_clk_in_p_pin]
set_property DIFF_TERM_ADV TERM_100 [get_ports chipscope_clk_in_p_pin]
set_property EQUALIZATION EQ_NONE [get_ports chipscope_clk_in_n_pin]
set_property IOSTANDARD LVDS15 [get_ports chipscope_clk_in_n_pin]
set_property DC_BIAS DC_BIAS_0 [get_ports chipscope_clk_in_n_pin]
set_property DIFF_TERM_ADV TERM_100 [get_ports chipscope_clk_in_n_pin]
set_property EQUALIZATION EQ_NONE [get_ports chipscope_clk_in_n_pin]
create_clock -period 5.000 [get_ports chipscope_clk_in_p_pin]


set_property CLOCK_DEDICATED_ROUTE ANY_CMT_REGION [get_nets int_clkin_rx_bufg]


#########################################################
#########       Placement   Constraints          ########
#########################################################

#####################
#### TX bank 706 ####
#####################

set_property PACKAGE_PIN BF23 [get_ports Tx_data_n0_bs0_p]
set_property PACKAGE_PIN BE22 [get_ports Tx_data_n0_bs1_n]
set_property PACKAGE_PIN BG25 [get_ports Tx_data_n0_bs2_p]
set_property PACKAGE_PIN BG24 [get_ports Tx_data_n0_bs3_n]
set_property PACKAGE_PIN BF21 [get_ports Tx_data_n0_bs4_p]
set_property PACKAGE_PIN BG20 [get_ports Tx_data_n0_bs5_n]

set_property PACKAGE_PIN BG21 [get_ports Tx_data_n1_bs0_p]
set_property PACKAGE_PIN BF22 [get_ports Tx_data_n1_bs1_n]
set_property PACKAGE_PIN BE21 [get_ports Tx_data_n1_bs2_p]
set_property PACKAGE_PIN BE20 [get_ports Tx_data_n1_bs3_n]
set_property PACKAGE_PIN BF24 [get_ports Tx_data_n1_bs4_p]
set_property PACKAGE_PIN BG23 [get_ports Tx_data_n1_bs5_n]

set_property PACKAGE_PIN BD23 [get_ports Tx_data_n2_bs0_p]
set_property PACKAGE_PIN BD24 [get_ports Tx_data_n2_bs1_n]

set_property PACKAGE_PIN BE25 [get_ports Tx_data_n2_bs2_p]
set_property PACKAGE_PIN BE24 [get_ports Tx_data_n2_bs3_n]
set_property PACKAGE_PIN BC22 [get_ports Tx_data_n2_bs4_p]
set_property PACKAGE_PIN BC21 [get_ports Tx_data_n2_bs5_n]

set_property PACKAGE_PIN BC23 [get_ports Tx_data_n3_bs0_p]
set_property PACKAGE_PIN BD22 [get_ports Tx_data_n3_bs1_n]
set_property PACKAGE_PIN BC20 [get_ports Tx_data_n3_bs2_p]
set_property PACKAGE_PIN BD20 [get_ports Tx_data_n3_bs3_n]
set_property PACKAGE_PIN BC25 [get_ports Tx_data_n3_bs4_p]
set_property PACKAGE_PIN BD25 [get_ports Tx_data_n3_bs5_n]

#set_property PACKAGE_PIN BC25 [get_ports Tx_data_n4_bs0_p]
#set_property PACKAGE_PIN BD25 [get_ports Tx_data_n4_bs1_n]
set_property PACKAGE_PIN AU24 [get_ports Tx_data_n4_bs2_p]
set_property PACKAGE_PIN AU23 [get_ports Tx_data_n4_bs3_n]
set_property PACKAGE_PIN AV22 [get_ports Tx_data_n4_bs4_p]
set_property PACKAGE_PIN AW21 [get_ports Tx_data_n4_bs5_n]

set_property PACKAGE_PIN AY22 [get_ports Tx_data_n5_bs0_p]
set_property PACKAGE_PIN AY23 [get_ports Tx_data_n5_bs1_n]
set_property PACKAGE_PIN AU21 [get_ports Tx_data_n5_bs2_p]
set_property PACKAGE_PIN AV21 [get_ports Tx_data_n5_bs3_n]
set_property PACKAGE_PIN AW24 [get_ports Tx_data_n5_bs4_p]
set_property PACKAGE_PIN AY25 [get_ports Tx_data_n5_bs5_n]


#######################
####  Rx bank 707  ####
#######################

set_property PACKAGE_PIN BB18 [get_ports Rx_data_n0_bs0_p]
set_property PACKAGE_PIN BC17 [get_ports Rx_data_n0_bs1_n]
set_property PACKAGE_PIN BF19 [get_ports Rx_data_n0_bs2_p]
set_property PACKAGE_PIN BG19 [get_ports Rx_data_n0_bs3_n]
set_property PACKAGE_PIN AU20 [get_ports Rx_data_n0_bs4_p]
set_property PACKAGE_PIN AU19 [get_ports Rx_data_n0_bs5_n]

set_property PACKAGE_PIN AM21 [get_ports Rx_data_n1_bs0_p]
set_property PACKAGE_PIN AM20 [get_ports Rx_data_n1_bs1_n]
set_property PACKAGE_PIN AT20 [get_ports Rx_data_n1_bs2_p]
set_property PACKAGE_PIN AR20 [get_ports Rx_data_n1_bs3_n]
set_property PACKAGE_PIN BF18 [get_ports Rx_data_n1_bs4_p]
set_property PACKAGE_PIN BG18 [get_ports Rx_data_n1_bs5_n]

set_property PACKAGE_PIN BB16 [get_ports strobe_p]        
set_property PACKAGE_PIN BC16 [get_ports strobe_n]        

set_property PACKAGE_PIN BC18 [get_ports Rx_data_n2_bs2_p]
set_property PACKAGE_PIN BD18 [get_ports Rx_data_n2_bs3_n]
set_property PACKAGE_PIN BF16 [get_ports Rx_data_n2_bs4_p]
set_property PACKAGE_PIN BG16 [get_ports Rx_data_n2_bs5_n]

set_property PACKAGE_PIN BE17 [get_ports Rx_data_n3_bs0_p]
set_property PACKAGE_PIN BD17 [get_ports Rx_data_n3_bs1_n]
set_property PACKAGE_PIN BB20 [get_ports Rx_data_n3_bs2_p]
set_property PACKAGE_PIN BB19 [get_ports Rx_data_n3_bs3_n]
set_property PACKAGE_PIN BA20 [get_ports Rx_data_n3_bs4_p]
set_property PACKAGE_PIN BA19 [get_ports Rx_data_n3_bs5_n]

#set_property PACKAGE_PIN BA20 [get_ports Rx_data_n4_bs0_p]
#set_property PACKAGE_PIN BA19 [get_ports Rx_data_n4_bs1_n]
set_property PACKAGE_PIN AR18 [get_ports Rx_data_n4_bs2_p]
set_property PACKAGE_PIN AT19 [get_ports Rx_data_n4_bs3_n]
set_property PACKAGE_PIN BE16 [get_ports Rx_data_n4_bs4_p]
set_property PACKAGE_PIN BF17 [get_ports Rx_data_n4_bs5_n]

set_property PACKAGE_PIN AN20 [get_ports Rx_data_n5_bs0_p]
set_property PACKAGE_PIN AN19 [get_ports Rx_data_n5_bs1_n]
set_property PACKAGE_PIN BE19 [get_ports Rx_data_n5_bs2_p]
set_property PACKAGE_PIN BD19 [get_ports Rx_data_n5_bs3_n]
set_property PACKAGE_PIN BA17 [get_ports Rx_data_n5_bs4_p]
set_property PACKAGE_PIN BA16 [get_ports Rx_data_n5_bs5_n]


#########################################################
#########       IOSTANDARD Settings              ########
#########################################################

#######################
#####  Tx IO STD  #####
#######################

set_property IOSTANDARD LVDS15 [get_ports Tx_data_n0_bs0_p]
set_property IOSTANDARD LVDS15 [get_ports Tx_data_n0_bs1_n]
set_property IOSTANDARD LVDS15 [get_ports Tx_data_n0_bs2_p]
set_property IOSTANDARD LVDS15 [get_ports Tx_data_n0_bs3_n]
set_property IOSTANDARD LVDS15 [get_ports Tx_data_n0_bs4_p]
set_property IOSTANDARD LVDS15 [get_ports Tx_data_n0_bs5_n]
set_property IOSTANDARD LVDS15 [get_ports Tx_data_n1_bs0_p]
set_property IOSTANDARD LVDS15 [get_ports Tx_data_n1_bs1_n]
set_property IOSTANDARD LVDS15 [get_ports Tx_data_n1_bs2_p]
set_property IOSTANDARD LVDS15 [get_ports Tx_data_n1_bs3_n]
set_property IOSTANDARD LVDS15 [get_ports Tx_data_n1_bs4_p]
set_property IOSTANDARD LVDS15 [get_ports Tx_data_n1_bs5_n]
set_property IOSTANDARD LVDS15 [get_ports Tx_data_n2_bs0_p]
set_property IOSTANDARD LVDS15 [get_ports Tx_data_n2_bs1_n]
set_property IOSTANDARD LVDS15 [get_ports Tx_data_n2_bs2_p]
set_property IOSTANDARD LVDS15 [get_ports Tx_data_n2_bs3_n]
set_property IOSTANDARD LVDS15 [get_ports Tx_data_n2_bs4_p]
set_property IOSTANDARD LVDS15 [get_ports Tx_data_n2_bs5_n]
set_property IOSTANDARD LVDS15 [get_ports Tx_data_n3_bs0_p]
set_property IOSTANDARD LVDS15 [get_ports Tx_data_n3_bs1_n]
set_property IOSTANDARD LVDS15 [get_ports Tx_data_n3_bs2_p]
set_property IOSTANDARD LVDS15 [get_ports Tx_data_n3_bs3_n]
set_property IOSTANDARD LVDS15 [get_ports Tx_data_n3_bs4_p]
set_property IOSTANDARD LVDS15 [get_ports Tx_data_n3_bs5_n]
#set_property IOSTANDARD LVDS15 [get_ports Tx_data_n4_bs0_p]
#set_property IOSTANDARD LVDS15 [get_ports Tx_data_n4_bs1_n]
set_property IOSTANDARD LVDS15 [get_ports Tx_data_n4_bs2_p]
set_property IOSTANDARD LVDS15 [get_ports Tx_data_n4_bs3_n]
set_property IOSTANDARD LVDS15 [get_ports Tx_data_n4_bs4_p]
set_property IOSTANDARD LVDS15 [get_ports Tx_data_n4_bs5_n]
set_property IOSTANDARD LVDS15 [get_ports Tx_data_n5_bs0_p]
set_property IOSTANDARD LVDS15 [get_ports Tx_data_n5_bs1_n]
set_property IOSTANDARD LVDS15 [get_ports Tx_data_n5_bs2_p]
set_property IOSTANDARD LVDS15 [get_ports Tx_data_n5_bs3_n]
set_property IOSTANDARD LVDS15 [get_ports Tx_data_n5_bs4_p]
set_property IOSTANDARD LVDS15 [get_ports Tx_data_n5_bs5_n]

#######################
#####  Rx IO STD  #####
#######################

set_property DIFF_TERM_ADV TERM_100 [get_ports Rx_data_n0_bs0_p]
set_property DIFF_TERM_ADV TERM_100 [get_ports Rx_data_n0_bs1_n]
set_property DIFF_TERM_ADV TERM_100 [get_ports Rx_data_n0_bs2_p]
set_property DIFF_TERM_ADV TERM_100 [get_ports Rx_data_n0_bs3_n]
set_property DIFF_TERM_ADV TERM_100 [get_ports Rx_data_n0_bs4_p]
set_property DIFF_TERM_ADV TERM_100 [get_ports Rx_data_n0_bs5_n]
set_property DIFF_TERM_ADV TERM_100 [get_ports Rx_data_n1_bs1_n]
set_property DIFF_TERM_ADV TERM_100 [get_ports Rx_data_n1_bs0_p]
set_property DIFF_TERM_ADV TERM_100 [get_ports Rx_data_n1_bs2_p]
set_property DIFF_TERM_ADV TERM_100 [get_ports Rx_data_n1_bs3_n]
set_property DIFF_TERM_ADV TERM_100 [get_ports Rx_data_n1_bs4_p]
set_property DIFF_TERM_ADV TERM_100 [get_ports Rx_data_n1_bs5_n]
set_property DIFF_TERM_ADV TERM_100 [get_ports strobe_n]
set_property DIFF_TERM_ADV TERM_100 [get_ports strobe_p]
set_property DIFF_TERM_ADV TERM_100 [get_ports Rx_data_n2_bs2_p]
set_property DIFF_TERM_ADV TERM_100 [get_ports Rx_data_n2_bs3_n]
set_property DIFF_TERM_ADV TERM_100 [get_ports Rx_data_n2_bs4_p]
set_property DIFF_TERM_ADV TERM_100 [get_ports Rx_data_n2_bs5_n]
set_property DIFF_TERM_ADV TERM_100 [get_ports Rx_data_n3_bs0_p]
set_property DIFF_TERM_ADV TERM_100 [get_ports Rx_data_n3_bs1_n]
set_property DIFF_TERM_ADV TERM_100 [get_ports Rx_data_n3_bs2_p]
set_property DIFF_TERM_ADV TERM_100 [get_ports Rx_data_n3_bs3_n]
set_property DIFF_TERM_ADV TERM_100 [get_ports Rx_data_n3_bs4_p]
set_property DIFF_TERM_ADV TERM_100 [get_ports Rx_data_n3_bs5_n]
#set_property DIFF_TERM_ADV TERM_100 [get_ports Rx_data_n4_bs1_n]
#set_property DIFF_TERM_ADV TERM_100 [get_ports Rx_data_n4_bs0_p]
set_property DIFF_TERM_ADV TERM_100 [get_ports Rx_data_n4_bs2_p]
set_property DIFF_TERM_ADV TERM_100 [get_ports Rx_data_n4_bs3_n]
set_property DIFF_TERM_ADV TERM_100 [get_ports Rx_data_n4_bs4_p]
set_property DIFF_TERM_ADV TERM_100 [get_ports Rx_data_n4_bs5_n]
set_property DIFF_TERM_ADV TERM_100 [get_ports Rx_data_n5_bs1_n]
set_property DIFF_TERM_ADV TERM_100 [get_ports Rx_data_n5_bs0_p]
set_property DIFF_TERM_ADV TERM_100 [get_ports Rx_data_n5_bs2_p]
set_property DIFF_TERM_ADV TERM_100 [get_ports Rx_data_n5_bs3_n]
set_property DIFF_TERM_ADV TERM_100 [get_ports Rx_data_n5_bs4_p]
set_property DIFF_TERM_ADV TERM_100 [get_ports Rx_data_n5_bs5_n]


set_property IOSTANDARD LVDS15 [get_ports Rx_data_n0_bs0_p]
set_property IOSTANDARD LVDS15 [get_ports Rx_data_n0_bs1_n]
set_property IOSTANDARD LVDS15 [get_ports Rx_data_n0_bs2_p]
set_property IOSTANDARD LVDS15 [get_ports Rx_data_n0_bs3_n]
set_property IOSTANDARD LVDS15 [get_ports Rx_data_n0_bs4_p]
set_property IOSTANDARD LVDS15 [get_ports Rx_data_n0_bs5_n]
set_property IOSTANDARD LVDS15 [get_ports Rx_data_n1_bs0_p]
set_property IOSTANDARD LVDS15 [get_ports Rx_data_n1_bs1_n]
set_property IOSTANDARD LVDS15 [get_ports Rx_data_n1_bs2_p]
set_property IOSTANDARD LVDS15 [get_ports Rx_data_n1_bs3_n]
set_property IOSTANDARD LVDS15 [get_ports Rx_data_n1_bs4_p]
set_property IOSTANDARD LVDS15 [get_ports Rx_data_n1_bs5_n]
set_property IOSTANDARD LVDS15 [get_ports strobe_n]
set_property IOSTANDARD LVDS15 [get_ports strobe_p]
set_property IOSTANDARD LVDS15 [get_ports Rx_data_n2_bs2_p]
set_property IOSTANDARD LVDS15 [get_ports Rx_data_n2_bs3_n]
set_property IOSTANDARD LVDS15 [get_ports Rx_data_n2_bs4_p]
set_property IOSTANDARD LVDS15 [get_ports Rx_data_n2_bs5_n]
set_property IOSTANDARD LVDS15 [get_ports Rx_data_n3_bs0_p]
set_property IOSTANDARD LVDS15 [get_ports Rx_data_n3_bs1_n]
set_property IOSTANDARD LVDS15 [get_ports Rx_data_n3_bs2_p]
set_property IOSTANDARD LVDS15 [get_ports Rx_data_n3_bs3_n]
set_property IOSTANDARD LVDS15 [get_ports Rx_data_n3_bs4_p]
set_property IOSTANDARD LVDS15 [get_ports Rx_data_n3_bs5_n]
#set_property IOSTANDARD LVDS15 [get_ports Rx_data_n4_bs0_p]
#set_property IOSTANDARD LVDS15 [get_ports Rx_data_n4_bs1_n]
set_property IOSTANDARD LVDS15 [get_ports Rx_data_n4_bs2_p]
set_property IOSTANDARD LVDS15 [get_ports Rx_data_n4_bs3_n]
set_property IOSTANDARD LVDS15 [get_ports Rx_data_n4_bs4_p]
set_property IOSTANDARD LVDS15 [get_ports Rx_data_n4_bs5_n]
set_property IOSTANDARD LVDS15 [get_ports Rx_data_n5_bs0_p]
set_property IOSTANDARD LVDS15 [get_ports Rx_data_n5_bs1_n]
set_property IOSTANDARD LVDS15 [get_ports Rx_data_n5_bs2_p]
set_property IOSTANDARD LVDS15 [get_ports Rx_data_n5_bs3_n]
set_property IOSTANDARD LVDS15 [get_ports Rx_data_n5_bs4_p]
set_property IOSTANDARD LVDS15 [get_ports Rx_data_n5_bs5_n]


set_property DC_BIAS DC_BIAS_0 [get_ports Rx_data_n0_bs0_p]
set_property DC_BIAS DC_BIAS_0 [get_ports Rx_data_n0_bs1_n]
set_property DC_BIAS DC_BIAS_0 [get_ports Rx_data_n0_bs2_p]
set_property DC_BIAS DC_BIAS_0 [get_ports Rx_data_n0_bs3_n]
set_property DC_BIAS DC_BIAS_0 [get_ports Rx_data_n0_bs4_p]
set_property DC_BIAS DC_BIAS_0 [get_ports Rx_data_n0_bs5_n]
set_property DC_BIAS DC_BIAS_0 [get_ports Rx_data_n1_bs0_p]
set_property DC_BIAS DC_BIAS_0 [get_ports Rx_data_n1_bs1_n]
set_property DC_BIAS DC_BIAS_0 [get_ports Rx_data_n1_bs2_p]
set_property DC_BIAS DC_BIAS_0 [get_ports Rx_data_n1_bs3_n]
set_property DC_BIAS DC_BIAS_0 [get_ports Rx_data_n1_bs4_p]
set_property DC_BIAS DC_BIAS_0 [get_ports Rx_data_n1_bs5_n]
set_property DC_BIAS DC_BIAS_0 [get_ports strobe_n]
set_property DC_BIAS DC_BIAS_0 [get_ports strobe_p]
set_property DC_BIAS DC_BIAS_0 [get_ports Rx_data_n2_bs2_p]
set_property DC_BIAS DC_BIAS_0 [get_ports Rx_data_n2_bs3_n]
set_property DC_BIAS DC_BIAS_0 [get_ports Rx_data_n2_bs4_p]
set_property DC_BIAS DC_BIAS_0 [get_ports Rx_data_n2_bs5_n]
set_property DC_BIAS DC_BIAS_0 [get_ports Rx_data_n3_bs0_p]
set_property DC_BIAS DC_BIAS_0 [get_ports Rx_data_n3_bs1_n]
set_property DC_BIAS DC_BIAS_0 [get_ports Rx_data_n3_bs2_p]
set_property DC_BIAS DC_BIAS_0 [get_ports Rx_data_n3_bs3_n]
set_property DC_BIAS DC_BIAS_0 [get_ports Rx_data_n3_bs4_p]
set_property DC_BIAS DC_BIAS_0 [get_ports Rx_data_n3_bs5_n]
#set_property DC_BIAS DC_BIAS_0 [get_ports Rx_data_n4_bs0_p]
#set_property DC_BIAS DC_BIAS_0 [get_ports Rx_data_n4_bs1_n]
set_property DC_BIAS DC_BIAS_0 [get_ports Rx_data_n4_bs2_p]
set_property DC_BIAS DC_BIAS_0 [get_ports Rx_data_n4_bs3_n]
set_property DC_BIAS DC_BIAS_0 [get_ports Rx_data_n4_bs4_p]
set_property DC_BIAS DC_BIAS_0 [get_ports Rx_data_n4_bs5_n]
set_property DC_BIAS DC_BIAS_0 [get_ports Rx_data_n5_bs0_p]
set_property DC_BIAS DC_BIAS_0 [get_ports Rx_data_n5_bs1_n]
set_property DC_BIAS DC_BIAS_0 [get_ports Rx_data_n5_bs2_p]
set_property DC_BIAS DC_BIAS_0 [get_ports Rx_data_n5_bs3_n]
set_property DC_BIAS DC_BIAS_0 [get_ports Rx_data_n5_bs4_p]
set_property DC_BIAS DC_BIAS_0 [get_ports Rx_data_n5_bs5_n]


set_property EQUALIZATION EQ_NONE [get_ports Rx_data_n0_bs0_p]
set_property EQUALIZATION EQ_NONE [get_ports Rx_data_n0_bs1_n]
set_property EQUALIZATION EQ_NONE [get_ports Rx_data_n0_bs2_p]
set_property EQUALIZATION EQ_NONE [get_ports Rx_data_n0_bs3_n]
set_property EQUALIZATION EQ_NONE [get_ports Rx_data_n0_bs4_p]
set_property EQUALIZATION EQ_NONE [get_ports Rx_data_n0_bs5_n]
set_property EQUALIZATION EQ_NONE [get_ports Rx_data_n1_bs0_p]
set_property EQUALIZATION EQ_NONE [get_ports Rx_data_n1_bs1_n]
set_property EQUALIZATION EQ_NONE [get_ports Rx_data_n1_bs2_p]
set_property EQUALIZATION EQ_NONE [get_ports Rx_data_n1_bs3_n]
set_property EQUALIZATION EQ_NONE [get_ports Rx_data_n1_bs4_p]
set_property EQUALIZATION EQ_NONE [get_ports Rx_data_n1_bs5_n]
set_property EQUALIZATION EQ_NONE [get_ports strobe_n]
set_property EQUALIZATION EQ_NONE [get_ports strobe_p]
set_property EQUALIZATION EQ_NONE [get_ports Rx_data_n2_bs2_p]
set_property EQUALIZATION EQ_NONE [get_ports Rx_data_n2_bs3_n]
set_property EQUALIZATION EQ_NONE [get_ports Rx_data_n2_bs4_p]
set_property EQUALIZATION EQ_NONE [get_ports Rx_data_n2_bs5_n]
set_property EQUALIZATION EQ_NONE [get_ports Rx_data_n3_bs0_p]
set_property EQUALIZATION EQ_NONE [get_ports Rx_data_n3_bs1_n]
set_property EQUALIZATION EQ_NONE [get_ports Rx_data_n3_bs2_p]
set_property EQUALIZATION EQ_NONE [get_ports Rx_data_n3_bs3_n]
set_property EQUALIZATION EQ_NONE [get_ports Rx_data_n3_bs4_p]
set_property EQUALIZATION EQ_NONE [get_ports Rx_data_n3_bs5_n]
#set_property EQUALIZATION EQ_NONE [get_ports Rx_data_n4_bs0_p]
#set_property EQUALIZATION EQ_NONE [get_ports Rx_data_n4_bs1_n]
set_property EQUALIZATION EQ_NONE [get_ports Rx_data_n4_bs2_p]
set_property EQUALIZATION EQ_NONE [get_ports Rx_data_n4_bs3_n]
set_property EQUALIZATION EQ_NONE [get_ports Rx_data_n4_bs4_p]
set_property EQUALIZATION EQ_NONE [get_ports Rx_data_n4_bs5_n]
set_property EQUALIZATION EQ_NONE [get_ports Rx_data_n5_bs0_p]
set_property EQUALIZATION EQ_NONE [get_ports Rx_data_n5_bs1_n]
set_property EQUALIZATION EQ_NONE [get_ports Rx_data_n5_bs2_p]
set_property EQUALIZATION EQ_NONE [get_ports Rx_data_n5_bs3_n]
set_property EQUALIZATION EQ_NONE [get_ports Rx_data_n5_bs4_p]
set_property EQUALIZATION EQ_NONE [get_ports Rx_data_n5_bs5_n]

