#
# Copyright (C) 2025, Advanced Micro Devices, Inc. All rights reserved.
# SPDX-License-Identifier: MIT
#

#Create the project in the output directory
create_project project_1 -force  -part xcvc1902-vsva2197-2MP-e-S

#Set the board part
set_property board_part xilinx.com:vck190:part0:3.2 [current_project]

#####Read all sources for building the project#####

#Generate the system BD that has only CIPS and DDR NOCs
source ../sources/bd/bd.tcl

#Read the RTL files that has XPM NMUs and NSUs instantiated along with traffic generators and BRAM 
#add_files ../sources/rtl
add_files ../sources/rtl

#Read Core Containers for IPs outside BD
add_files ../sources/manage_ip_xcix_prj/axi_bram_ctrl_pl_slave_from_pl_master.xcix
add_files ../sources/manage_ip_xcix_prj/axi_bram_ctrl_pl_slave_from_ps.xcix
add_files ../sources/manage_ip_xcix_prj/axis_vio_pl_master_to_ddr.xcix
add_files ../sources/manage_ip_xcix_prj/axis_vio_pl_master_to_pl_slave.xcix
add_files ../sources/manage_ip_xcix_prj/axis_vio_pl_master_to_ps.xcix
add_files ../sources/manage_ip_xcix_prj/axis_MxN_vio.xcix
add_files ../sources/manage_ip_xcix_prj/axi_tg_pl_to_pl.xcix
add_files ../sources/manage_ip_xcix_prj/axi_tg_pl_to_ps.xcix
add_files ../sources/manage_ip_xcix_prj/axi_tg_pl_master_to_ddr.xcix
 

#Read the XDC files for creating NoC connection, setting its QoS settings and the aperture of XPM NSUs. 
add_files -fileset constrs_1 ../sources/xdc/noc_constraints.xdc


#Read the XDC files that has constraints for creating ILAs and for connecting them to debug hub in the design. This constraint is auto-generated by the tool based on "Set up Debug" flow.
add_files -fileset constrs_1 ../sources/xdc/design_1_wrapper_debug.xdc

#####Set the USED_IN {synthesis_pre} for NoC constraints#####
set_property USED_IN {synthesis_pre} [get_files noc_constraints.xdc]

#####Generate targets : BD######
generate_target all [get_files design_1.bd]


##Launch Synthesis/Implementation and WDI. 
#start_gui
launch_runs synth_1 -jobs 16
wait_on_run synth_1 
exit
