#
# Copyright (C) 2024, Advanced Micro Devices, Inc. All rights reserved.
# SPDX-License-Identifier: X11
#

#Create the project in the output directory
create_project project_1 -force  -part xcvh1582-vsva3697-2MP-e-S

#Set the board part
set_property board_part xilinx.com:vhk158:part0:1.1 [current_project]

#####Read all sources for building the project#####

#Generate the system BD that has only CIPS and DDR NOCs
source ../sources/bd/bd.tcl

#Read the RTL files that has XPM NMUs and NSUs instantiated along with traffic generators and BRAM 
import_files ../sources/rtl

#Generate the XCI files for BRAMs, Performance Traffic Generators and VIO IPs
source ../sources/ip/perf_axi_tg_pl_bli_to_hbm.tcl
source ../sources/ip/perf_axi_tg_pl_vnoc_to_hbm.tcl
source ../sources/ip/vio_pl_master_to_hbm.tcl

#Read the simulation testbench files to sim_1 fileset only
import_files -fileset sim_1 ../sources/testbench

#Read the XDC files for creating NoC connection, setting its QoS settings and the aperture of XPM NSUs. 
import_files -fileset constrs_1 ../sources/xdc/noc_constraints.xdc

#Read the XDC files that has constraints for creating ILAs and for connecting them to debug hub in the design. This constraint is auto-generated by the tool based on "Set up Debug" flow.
import_files -fileset constrs_1 ../sources/xdc/top_debug.xdc

######Set the USED_IN {synthesis_pre} for NoC constraints#####
set_property USED_IN {synthesis_pre} [get_files ./project_1.srcs/constrs_1/imports/xdc/noc_constraints.xdc]

######Generate all targets : XCI/BD######
generate_target {synthesis instantiation_template} [get_files {vio_pl_master_to_hbm.xci perf_axi_tg_pl_bli_to_hbm.xci perf_axi_tg_pl_vnoc_to_hbm.xci design_1.bd}]

###Updating the sourcefile set 
update_compile_order -fileset sources_1

###### Validate the NoC to see the project level NoC endpoints and paths
validate_noc

###Launch Synthesis/Implementation and WDI. 
launch_runs impl_1 -to_step write_device_image -jobs 16
wait_on_run impl_1
exit
