set_property PACKAGE_PIN L19 [get_ports reset]
set_property PACKAGE_PIN AW25 [get_ports rs232_uart_rxd]
set_property PACKAGE_PIN BB21 [get_ports rs232_uart_txd]
set_property PACKAGE_PIN D21 [get_ports {dip_switches_4bits_tri_i[3]}]
set_property PACKAGE_PIN J16 [get_ports {dip_switches_4bits_tri_i[2]}]
set_property PACKAGE_PIN G16 [get_ports {dip_switches_4bits_tri_i[1]}]
set_property PACKAGE_PIN B17 [get_ports {dip_switches_4bits_tri_i[0]}]
set_property PACKAGE_PIN E12 [get_ports default_250mhz_clk1_clk_p]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores design_1_i/debug_bridge_0/inst/xsdbm]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores design_1_i/debug_bridge_0/inst/xsdbm]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores design_1_i/debug_bridge_0/inst/xsdbm]
connect_debug_port design_1_i/debug_bridge_0/inst/xsdbm/clk [get_nets design_1_i/debug_bridge_0/inst/clk]
